# Generated by Django 4.2 on 2025-07-26 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca1', models.PositiveIntegerField(blank=True, null=True)),
                ('ca2', models.PositiveIntegerField(blank=True, null=True)),
                ('et', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('remark', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecretCodeNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000)])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=8)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('form', models.CharField(choices=[(None, None), ('Form 1', 'Form One'), ('Form 2', 'Form Two'), ('Form 3', 'Form Three'), ('Form 4', 'Form Four')], max_length=7)),
                ('stream', models.CharField(choices=[(None, None), ('A', 'A'), ('B', 'B')], max_length=1)),
                ('joined_school_at', models.DateField(blank=True, null=True, verbose_name='Started on')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('guardian_name', models.CharField(max_length=30)),
                ('guardian_phone', models.CharField(max_length=12)),
                ('guardian_email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_form', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)], verbose_name='Form')),
                ('subject_bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=8)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=8, null=True)),
                ('phone', models.CharField(max_length=12)),
                ('joined_at', models.DateField(blank=True, null=True, verbose_name='Joined on')),
                ('experience', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Years Of Experience')),
                ('office', models.CharField(blank=True, max_length=80, null=True, verbose_name='Office')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('teachers_code', models.CharField(blank=True, max_length=8, verbose_name='Teachers Secret Code')),
                ('form_teacher', models.CharField(blank=True, choices=[(None, None), ('Form 1', 'Form One'), ('Form 2', 'Form Two'), ('Form 3', 'Form Three'), ('Form 4', 'Form Four')], max_length=7, null=True, verbose_name='Form Teacher')),
                ('ft_stream', models.CharField(blank=True, choices=[(None, None), ('A', 'A'), ('B', 'B')], max_length=1)),
                ('form_assigned', models.CharField(blank=True, choices=[(None, None), ('Form 1', 'Form One'), ('Form 2', 'Form Two'), ('Form 3', 'Form Three'), ('Form 4', 'Form Four')], max_length=7)),
                ('stream1', models.CharField(blank=True, choices=[(None, None), ('A', 'A'), ('B', 'B')], max_length=1, null=True)),
                ('form_assigned2', models.CharField(blank=True, choices=[(None, None), ('Form 1', 'Form One'), ('Form 2', 'Form Two'), ('Form 3', 'Form Three'), ('Form 4', 'Form Four')], max_length=7, null=True)),
                ('stream2', models.CharField(blank=True, choices=[(None, None), ('A', 'A'), ('B', 'B')], max_length=1, null=True)),
                ('form_assigned3', models.CharField(blank=True, choices=[(None, None), ('Form 1', 'Form One'), ('Form 2', 'Form Two'), ('Form 3', 'Form Three'), ('Form 4', 'Form Four')], max_length=7, null=True)),
                ('stream3', models.CharField(blank=True, choices=[(None, None), ('A', 'A'), ('B', 'B')], max_length=1, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_code', models.CharField(max_length=10)),
            ],
        ),
    ]
