# Generated by Django 4.2 on 2025-08-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_grade_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='ca1_out_of',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='ca2_out_of',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='et_out_of',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='remark',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
