# Generated by Django 4.2 on 2025-08-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_grade_ca1_out_of_grade_ca2_out_of_grade_et_out_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='ca1_out_of',
            field=models.PositiveIntegerField(blank=True, default=40),
        ),
        migrations.AlterField(
            model_name='grade',
            name='ca2_out_of',
            field=models.PositiveIntegerField(blank=True, default=40),
        ),
        migrations.AlterField(
            model_name='grade',
            name='et_out_of',
            field=models.PositiveIntegerField(blank=True, default=100),
        ),
    ]
