# Generated by Django 4.2 on 2025-08-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_grade_ca1_out_of_alter_grade_ca2_out_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='remark',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
